import { hashSync } from "bcrypt-ts-edge";

const sampleData = {

  users: [
    {
      name: 'Khalid',
      email: 'khalid@gmail.com',
      password: hashSync('111111', 10),
      role: 'admin',
    },
    {
      name: 'Ali',
      email: 'ali@gmail.com',
      password: hashSync('111111', 10),
      role: 'user',
    },
  ],

  products: [
    {
      name: 'arduino kit',
      slug: 'arduino-kit',
      category: "Electronics",
      description: 'Complete Arduino development kit for beginners',
      images: [
        '/images/sample-products/k-1.avif',
        '/images/sample-products/k-2.avif',
        '/images/sample-products/k-3.avif',
        '/images/sample-products/k-4.avif',
      ],
      price: 9.999,
      brand: 'Arduino',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'k-1.avif',
    },
    {
      name: 'bridboard',
      slug: 'bridboard',
      category: "Electronics",
      description: 'Breadboard for prototyping and circuit testing',
      images: [
        '/images/sample-products/b-1.avif',
        '/images/sample-products/b-2.avif',
      ],
      price: 5.999,
      brand: 'Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'b-1.avif',
    },
    {
      name: 'arduino',
      slug: 'arduino',
      category: "Electronics",
      description: 'Complete Arduino development kit for beginners',
      images: [
        '/images/sample-products/r-1.avif',
        '/images/sample-products/r-2.avif',
        '/images/sample-products/r-3.avif',
      ],
      price: 9.950,
      brand: 'Arduino',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 9.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 9.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 9.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
